framework:
    messenger:
        # Konfiguracja transportów
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true # Automatycznie utworzy tabelę messenger_messages
            sync: 'sync://'
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                # Opcjonalnie: doctrine_transaction (jeśli komenda ma być w transakcji)
            query.bus:
                middleware:
                # Query nie powinno niczego zapisywać
            event.bus:
                default_middleware:
                    allow_no_handlers: true
        # Routing - mówimy Symfony, że to konkretne polecenie ma iść w tło
        routing:
            'App\Modules\PropertyCatalog\Application\Command\ProcessPropertyImageCommand': async
